### ISSUE TITLE
Global registry API

### ISSUE THREAD

**Issue by brunobord** [peopledoc/workalendar#375]
The current state of the global registry annoys me a bit.

1. it returns ``OrderedDict``s instead of plain built-in ``dict``s for no apparent reasons.
2. It could mimic a dictionary, but instead it has a sub-dictionary, called ``region_registry``, that somehow "hides" the "true" registry (i.e. the full list of calendars registered).
3. It has an ``items()`` method that doesn't behave like the standard ``items()`` method of a dictionary-like object. It requires an argument to search for items.
4. It doesn't have a ``get()`` method, but it's named ``get_calendar_class()``.

Each point could lead to a series of changes in its API. Considering that I've already warned workalendar users that the registry return type would change, I'd like to make a case on each of the above points.

## 1 - ``dict``s instead of ``OrderedDict``s

The branch is already ready, no big deal.

## 2 & 3 & 4 - dictionary interface

Here are the changes I envision:

* ``items()`` would return the full list of calendars.
* ``items([list of codes...])`` would return a dictionary of calendars whose codes are in the registry. Unkown codes would be skipped. Sub-regions codes would be allowed (e.g.: ``items(['CA-AB', 'AU-NT'])`` would return the Canada Alberta & Australia Northern Territory calendars)
* ``items([list of codes...], include_subregions=True)`` same as above, except that you would get also subregions when they exist.
* ``get_calendar_class()`` would be aliased to ``get()``, deprecated and then removed.

The whole process can be handled via deprecation warnings and careful versionning. It could also be done in one shot, switching from the 5.x series to 6.0.

## Beyond

Thinking out loud, not a priority, and maybe overkill:

Maybe this registry could also be an object that inherits from ``dict()`` objects? Or maybe make it an ``Iterable`` to ease map/filter operations?

----

## Task list

* [x] ``dict``s instead of ``OrderedDict``s #391
* [x] Deprecate `items()` in favor of `get_calendars()` #403
* [x] Allow `get_calendars()` to give empty `region_codes` argument, to retrieve the full data #403
* [x] Remove the `registry.items()` method #491
* [x] Alias `get_calendar_class` into `get()` #418
* [x] Completely drop `registry.get_calendar_class` method #495
