### ISSUE TITLE
Spain: calendars for autonomous regions

### ISSUE THREAD

**Issue by brunobord** [peopledoc/workalendar#531]
The wikipedia page about Public holidays in Spain[^1] is now displaying holidays for regions other than Catalonia.

Maybe it's time to add them all...

* Add the calendars with tests
* Add ISO registry code (test the code)

### TODO

- [x] Andalusia
- [x] Aragon
- [x] Castile and León
- [x] Castilla–La Mancha
- [x] Canary Islands
- [x] Catalonia
- [x] Extremadura
- [x] Galicia (Spain)
- [x] Balearic Islands
- [x] La Rioja
- [x] Community of Madrid
- [x] Region of Murcia
- [x] Navarre
- [x] Asturias
- [x] Basque Country
- [x] Cantabria
- [x] Valencian Community

[^1]: https://en.wikipedia.org/wiki/Public_holidays_in_Spain

**Comment by brunobord** [comment]
Small doubts for ISO codes for Asturias & Murcia.
I've asked @ainarela (super Spanish coworker) and she replied:

> so in Asturias seems like one is for the province, and the other for the autonomous community… 

> I would take the one for the autonomous community, because that is above the province administratively speaking: autonomous communities contain provinces communities can contain several provinces, but in the case of Asturias there is only one, with the same name, so for sure the public holidays are the same but it makes more sense I think to use ES-AS I think

> ok, and same thing for Murcia actually :) wikipedia says “region” but it should mean the same as “autonomous community”, and Murcia region has only one province. I think you’re good with ES-MC

**Comment by brunobord** [comment]
released and uploaded on PyPI! 

* https://github.com/peopledoc/workalendar/releases/tag/12.1.0
* https://pypi.org/project/workalendar/12.1.0/
